### ISSUE TITLE
SocketTimeoutException while sending SMS

### ISSUE THREAD

**Issue by manojsinghal2003** [infobip/infobip-api-java-client#11]
Hi, 

We are getting below error when sending an SMS. 

with cause = 'java.net.SocketTimeoutException: connect timed out' and exception = 'connect timed out'

retrofit.RetrofitError: connect timed out
        at retrofit.RetrofitError.networkError(RetrofitError.java:27)
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
        at infobip.api.client.$Proxy213.execute(Unknown Source)
        at infobip.api.client.SendSingleTextualSms.execute(SendSingleTextualSms.java:36)

Please help us to fix it.

**Comment by Antolius** [comment]
Hi!

Might be a case of slow internet connection between where you are running your service and the Infobip API. Depending on where you are encountering this issue (your local development machine vs your production environment, for example) you might need to look into this one further.

If you do find the issue persists on your production environment you can contact our [support](https://dev.infobip.com/support) at support@infobip.com. They can assist you with finding Infobip API location closest to you (default location is Europe).

As a quick fix "solution" you can specify timeout intervals in the [configuration](https://github.com/infobip/infobip-api-java-client/blob/master/src/main/java/infobip/api/config/Configuration.java#L5-L6) that you use to instantiate the client. For example:

```java
Configuration configuration = new ApiKeyAuthConfiguration(API_KEY);
configuration.setConnectionTimeout(100_000); // 10 x default value, in milliseconds
SendSingleTextualSms client = new SendSingleTextualSms(configuration);
SMSResponse response = client.execute(constructRequestBody());
```

**Comment by hkozacinski** [comment]
Closing this issue due to inactivity. If you experience more problems, feel free to reopen this issue or create a new one.
